---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(dbplyr)
library(lubridate)
library(tibble)
library(ggplot2)
library(stringr)
library(gridExtra)
library(network)
library(ggraph)
library(visNetwork)
library(networkD3)
library(igraph)
library(tidygraph)
library(cluster)
library(fpc)
library(plotly)
library(cluster)
library(mclust)
library(factoextra)
library(anomalize)
library(boot)
library(leaps)
library(stargazer)
```

```{r}
pathname <- '/home/alex/S2DS/FSA/handover/data/'
#Mate
#filename <- 'all_data__090300_201401-201602_total_dump_00.RData'
#Cheese
#filename <- 'all_data__040640_201401-201601_total_dump_00.RData'
#Beer
#filename <- 'all_data__220300_201401-201601_total_dump_00.RData'
#Beans
#filename <- 'all_data__071022_201501-201601_total_dump_00.RData'
#Rice
filename <- 'all_data__1006_201001-201301_total_dump_00.RData'
#Junk
#filename <- 'network_012008-122016_28276.RData'
dump_files <- FALSE
route <- paste(pathname,filename,sep='')
load(route)

node_data <- data$node_data#old "all_info"
edge_data <- data$edge_data#old "si"
```

```{r}
source("/home/alex/S2DS/FSA/handover/modeling/build_network.R")
source("/home/alex/S2DS/FSA/handover/modeling/model_linear.R")
source("/home/alex/S2DS/FSA/handover/modeling/model_linear_reduced.R")
source("/home/alex/S2DS/FSA/handover/modeling/model_kmeans.R")
source("/home/alex/S2DS/FSA/handover/modeling/model_kmeans_reduced.R")
source("/home/alex/S2DS/FSA/handover/modeling/dump_lm_sum.R")
#
source("/home/alex/S2DS/FSA/handover/modeling/model_linear_janis.R")
source("/home/alex/S2DS/FSA/handover/modeling/model_linear_janis_steroids.R")
#
source("/home/alex/S2DS/FSA/handover/modeling/model_kmeans_janis.R")
source("/home/alex/S2DS/FSA/handover/modeling/model_kmeans_janis_steroids.R")
```

```{r}
toplim <- 50
p1 <- ggplot(data = node_data) + geom_point(mapping = aes(
      y=overall_flux_n,
      x=max_influx_n,color=ratio),
      size=0.75) +
      scale_colour_gradientn(colours=rainbow(4)) + xlim(0,toplim) + ylim(0,toplim) +
      ggtitle('Mate: normalized trade fluxes') + ylab('Overall') + xlab('Maximum influx')
p2 <- ggplot(data = node_data) + geom_point(mapping = aes(
      y=overall_flux_n,
      x=max_outflux_n,color=ratio),
      size=0.75) +
      scale_colour_gradientn(colours=rainbow(4)) + xlim(0,toplim) + ylim(0,toplim) +
      ggtitle('Mate: normalized trade fluxes') + ylab('Overall') + xlab('Maximum outflux')
p3 <- ggplot(data = node_data) + geom_point(mapping = aes(
      y=overall_flux_n,
      x=ave_influx_n,color=ratio),
      size=0.75) +
      scale_colour_gradientn(colours=rainbow(4)) + xlim(0,toplim) + ylim(0,toplim) +
      ggtitle('Mate: normalized trade fluxes') + ylab('Overall') + xlab('Average influx')
p4 <- ggplot(data = node_data) + geom_point(mapping = aes(
      y=overall_flux_n,
      x=ave_outflux_n,color=ratio),
      size=0.75) +
      scale_colour_gradientn(colours=rainbow(4)) + xlim(0,toplim) + ylim(0,toplim) +
      ggtitle('Mate: normalized trade fluxes') + ylab('Overall') + xlab('Average outflux')
grid.arrange(p1,p2,p3,p4,nrow=2)
```
```{r}
toplim <- 15
ggplot(data = node_data) + geom_point(mapping = aes(y=ave_influx_n,
      x=max_influx_n,color=ratio),
      size=0.75) +
      scale_colour_gradientn(colours=rainbow(4)) + xlim(0,toplim) + ylim(0,toplim) +
      ggtitle('Beer: normalized trade fluxes') + ylab('Ave influx') + xlab('Max influx')
```

```{r}
lmf.results <- model_linear(node_data)
```

```{r}
lmr.results <- model_linear_reduced(node_data)
```

```{r}
lmj.results <- model_linear_janis(node_data)
```

```{r}
lmjs.results <- model_linear_janis_steroids(node_data)
```

###summary(lmf.results[[5]])

```{r}
build_network(edge_data,1,85)
```

```{r}
if(dump_files){
pp <- '/home/alex/Dropbox/pivigo/report/data/beans/'
stargazer(  lmf.results[[1]], omit.stat=c("LL","ser","f"), ci=FALSE, single.row=TRUE,        out=paste(pp,'lmf_sum_00_pow1.tex',sep=''))
stargazer(t(lmf.results[[2]]$outmat), omit.stat=c("LL","ser","f"), ci=FALSE, single.row=TRUE,out=paste(pp,'lmf_reg_00_pow1.tex',sep=''))
stargazer(  lmf.results[[3]], omit.stat=c("LL","ser","f"), ci=FALSE, single.row=TRUE,        out=paste(pp,'lmf_sum_00_pow2.tex',sep=''))
stargazer(t(lmf.results[[4]]$outmat), omit.stat=c("LL","ser","f"), ci=FALSE, single.row=TRUE,out=paste(pp,'lmf_reg_00_pow2.tex',sep=''))
stargazer(  lmf.results[[5]], omit.stat=c("LL","ser","f"), ci=FALSE, single.row=TRUE,        out=paste(pp,'lmf_sum_00_pow3.tex',sep=''))
stargazer(t(lmf.results[[6]]$outmat), omit.stat=c("LL","ser","f"), ci=FALSE, single.row=TRUE,out=paste(pp,'lmf_reg_00_pow3.tex',sep=''))
#
stargazer(  lmr.results[[1]], omit.stat=c("LL","ser","f"), ci=FALSE, single.row=TRUE,        out=paste(pp,'lmr_sum_00_pow1.tex',sep=''))
stargazer(t(lmr.results[[2]]$outmat), omit.stat=c("LL","ser","f"), ci=FALSE, single.row=TRUE,out=paste(pp,'lmr_reg_00_pow1.tex',sep=''))
stargazer(  lmr.results[[3]], omit.stat=c("LL","ser","f"), ci=FALSE, single.row=TRUE,        out=paste(pp,'lmr_sum_00_pow2.tex',sep=''))
stargazer(t(lmr.results[[4]]$outmat), omit.stat=c("LL","ser","f"), ci=FALSE, single.row=TRUE,out=paste(pp,'lmr_reg_00_pow2.tex',sep=''))
stargazer(  lmr.results[[5]], omit.stat=c("LL","ser","f"), ci=FALSE, single.row=TRUE,        out=paste(pp,'lmr_sum_00_pow3.tex',sep=''))
stargazer(t(lmr.results[[6]]$outmat), omit.stat=c("LL","ser","f"), ci=FALSE, single.row=TRUE,out=paste(pp,'lmr_reg_00_pow3.tex',sep=''))
}
```

```{r}
ans <- model_kmeans(node_data,'United Kingdom',5)
print(ans[2])
```

```{r}
ans <- model_kmeans_reduced(node_data,'United Kingdom',5)
print(ans[2])
```

```{r}
ans <- model_kmeans_janis(node_data,'United Kingdom',5)
print(ans[2])
```

```{r}
ans <- model_kmeans_janis_steroids(node_data,'United Kingdom',5)
print(ans[2])
```









