---
title: Linear and k-means modeling
author: "Àlex Fabregat"
output:
  pdf_document:
    latex_engine: xelatex
  html_notebook: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = FALSE, echo=FALSE, message = FALSE)
```
```{r,message=FALSE,warning=FALSE,echo=FALSE}
library(RPostgreSQL)
library(tidyverse)
library(dbplyr)
library(rjson)
library(DBI)
library(lubridate)
library(tibble)
library(ggplot2)
library(stringr)
library(gridExtra)
library(network)
library(ggraph)
library(visNetwork)
library(networkD3)
library(igraph)
library(tidygraph)
library(cluster) 
library(fpc)
library(plotly)
library(cluster)
library(factoextra)
library(boot)
library(leaps)
```

# Pick a commodity.
It is necessary to generate a bunch of local commodity csv files.
```{r}
#pathname <- "../Chicken/"
#filename <- "world_chicken_data.csv"
pathname <- "../"
filename <- "Comtrade_all.csv"
#
route <- paste(pathname,filename,sep="")
```

# Generate the data frame with all the node variables.
```{r,echo = TRUE}
source("model_get_data.R")
all_info <- model_get_data(route)
```

# Do the k-means
Pick a country and it'll return an ordered list of the "most similar" countries.
```{r, echo = TRUE}
source("model_kmeans.R")
km <- model_kmeans(all_info, "United Kingdom")
print(km[1:5,])
```

# Fit a linear model
```{r, echo = TRUE}
source("model_linear.R")
lm.fit <- model_linear(all_info)
#summary(lm.fit)
```

### Now test the model against a (country, period) pair
Let me cheat a bit here and pick a really good pair :)
```{r}
pick_a_month   <- 201502
pick_a_country <- "Spain"
test <- all_info %>% filter(period == pick_a_month) %>%
                     filter(node == pick_a_country) %>%
                     select(overall_flux,deg_in_wei, deg_out_wei, degree_net, bet_val, tri_no, eigen_val, ratio)
ml <- predict(lm.fit,test[,2:ncol(test)], interval = "prediction")
print(paste("Observed, predicted and error for overall trade value in billions $US: ", 
            round(ml[1],digits=5),", ",
            round(test[,1]/1e9,digits=5),", ",
            round(100*abs(ml[1]-test[,1]/1e9)/(test[,1]/1e9),digits=2),
            "%", sep=""))
```

Now, let's show a bad one :(
```{r}
pick_a_month   <- 201402
pick_a_country <- "Italy"
test <- all_info %>% filter(period == pick_a_month) %>%
                     filter(node == pick_a_country) %>%
                     select(overall_flux,deg_in_wei, deg_out_wei, degree_net, bet_val, tri_no, eigen_val, ratio)
ml <- predict(lm.fit,test[,2:ncol(test)], interval = "prediction")
print(paste("Observed, predicted and error for overall trade value in billions $US: ", 
            round(ml[1],digits=5),", ",
            round(test[,1]/1e9,digits=5),", ",
            round(100*abs(ml[1]-test[,1]/1e9)/(test[,1]/1e9),digits=2),
            "%", sep=""))
```
