---
title: Modelling of International chicken trade and identification of anomalies via k-means
author: "Phoebe"
output:
  html_document: default
  pdf_document:
    latex_engine: xelatex
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = FALSE, echo=TRUE)
```

```{r,message=FALSE,warning=FALSE,echo=FALSE}
library(RPostgreSQL)
library(tidyverse)
library(dbplyr)
library(rjson)
library(DBI)
library(lubridate)
library(tibble)
library(ggplot2)
library(stringr)
library(gridExtra)
library(network)
library(ggraph)
library(visNetwork)
library(networkD3)
library(igraph)
library(tidygraph)
library(cluster) 
library(fpc)
library(lubridate)
library(rgl)
library(anomalize)
```

# read chicken csv and prepare data
```{r}
chicken_data <- read.csv(file="Chicken_data_PM.csv",header=TRUE)  
```

# Normalize total influx and outflux by the period mean
```{r}
Chicken_data_normalised <- chicken_data %>% group_by(period) %>%
  mutate(tot_in_wei_n = tot_in_wei/mean(tot_in_wei)) %>%
  mutate(tot_out_wei_n = tot_out_wei/mean(tot_out_wei)) %>%
  mutate(period_date = ymd(paste(as.character(period),"01",sep=""))) %>%
  mutate(degree_net = deg_out_wei - deg_in_wei) %>%
  mutate(overall_flux = tot_out_wei + tot_in_wei) %>%
  mutate(month = month(period_date)) %>%
  ungroup()
```


#Do some plots

```{r}
selected_countries <- c("Germany","Spain","Netherlands","United Kingdom")
ggplot(Chicken_data_normalised %>% filter(node %in% selected_countries)) + 
     geom_point(aes(
        x     = period_date,
        y     = ratio,
        color = deg_out_wei-deg_in_wei,
        size  = tot_in_wei_n,
        shape = node
      )) + 
        scale_colour_gradientn(colours=rainbow(4)) +
  ylim(-1, 1)
```

#Do some plots - look at betweenness

```{r}
selected_countries <- c("Germany","Spain")
ggplot(Chicken_data_normalised %>% filter(node %in% selected_countries)) + 
     geom_point(aes(
        x     = period_date,
        y     = bet_val,
        color = deg_out_wei-deg_in_wei,
        size  = tot_in_wei_n,
        shape = node
      )) + 
        scale_colour_gradientn(colours=rainbow(4)) 
```
lots of jumping about so many too difficult to find anomalies?

#try out anomalise on ratio data
```{r}
germany_chicken <- Chicken_data_normalised %>% filter(node == "Germany") %>% select(period_date, ratio, bet_val, degree_val, tri_no, eigen_val)
#use time decompose if using a time series to remove trends overtime
germany_chicken_notime <- time_decompose(germany_chicken, target=ratio) 

anomalize(germany_chicken_notime, target=remainder,alpha=50) -> germany_summary
germany_anomalies <- germany_summary %>% filter(anomaly == "Yes")
germany_anomalies
```
#plot everything
```{r}
selected_countries_new = c("United Kingdom", "Germany", "Spain", "France", "Mexico", "Netherlands")
Chicken_data_normalised %>% filter(node %in% selected_countries_new)  %>%
ggplot(aes(period_date, ratio)) +
  geom_point(color = "#2c3e50", alpha=0.25) +
  facet_wrap(~node, ncol=3) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 30, hjust=1)) +
  labs(title = "Node ratios over time")
```

#twitter - iqr
```{r}
#filter columns
selected_countries_new = c("United Kingdom", "Germany", "Spain", "France", "Mexico", "Netherlands")
Chicken_data_simple <- Chicken_data_normalised  %>%
  select(period_date, ratio, node) %>%
   filter(node %in% selected_countries_new) %>%
  group_by(node)


anomaly_summary <-Chicken_data_simple %>% 
            time_decompose(ratio, method = "twitter") %>% 
            anomalize(remainder, alpha = 1, method = "iqr",  verbose = TRUE) 

#anomalies <- anomaly_summary %>% filter(anomaly == "Yes") %>% print

anomaly_summary %>% filter(node == "Germany") %>% ungroup %>% plot_anomaly_decomposition 

anomaly_summary %>% time_recompose() %>%
  plot_anomalies(time_recomposed = TRUE, ncol=3, color_no = "purple", color_yes = "orange", alpha_ribbon = 1)
```
#twitter - gesd
```{r}
#filter columns
selected_countries_new = c("United Kingdom", "Germany", "Spain", "France", "Mexico", "Netherlands")
Chicken_data_simple <- Chicken_data_normalised  %>%
  select(period_date, ratio, node) %>%
   filter(node %in% selected_countries_new) %>%
  group_by(node)


anomaly_summary <-Chicken_data_simple %>% 
            time_decompose(ratio, method = "twitter") %>% 
            anomalize(remainder, alpha = 1, method = "gesd",  verbose = TRUE) 

#anomalies <- anomaly_summary %>% filter(anomaly == "Yes") %>% print

anomaly_summary %>% filter(node == "Germany") %>% ungroup %>% plot_anomaly_decomposition 

anomaly_summary %>% time_recompose() %>%
  plot_anomalies(time_recomposed = TRUE, ncol=3, color_no = "purple", color_yes = "orange", alpha_ribbon = 1)
```
#stl- iqr
```{r}
#filter columns
selected_countries_new = c("United Kingdom", "Germany", "Spain", "France", "Mexico", "Netherlands")
Chicken_data_simple <- Chicken_data_normalised  %>%
  select(period_date, ratio, node) %>%
   filter(node %in% selected_countries_new) %>%
  group_by(node)


anomaly_summary <-Chicken_data_simple %>% 
            time_decompose(ratio, method = "stl") %>% 
            anomalize(remainder, alpha = 0.3, method = "iqr") 

#anomalies <- anomaly_summary %>% filter(anomaly == "Yes") %>% print

anomaly_summary %>% filter(node == "Netherlands") %>% ungroup %>% plot_anomaly_decomposition 

anomaly_summary %>% time_recompose() %>%
  plot_anomalies(time_recomposed = TRUE, ncol=3, color_no = "purple", color_yes = "orange", alpha_ribbon = 1)
```
#stl - gesd
```{r}
#filter columns
selected_countries_new = c("United Kingdom", "Germany", "Spain", "France", "Mexico", "Netherlands")
Chicken_data_simple <- Chicken_data_normalised  %>%
  select(period_date, ratio, node) %>%
   filter(node %in% selected_countries_new) %>%
  group_by(node)


anomaly_summary <-Chicken_data_simple %>% 
            time_decompose(ratio, method = "stl") %>% 
            anomalize(remainder, alpha = 5, method = "iqr") 

#anomalies <- anomaly_summary %>% filter(anomaly == "Yes") %>% print

anomaly_summary %>% filter(node == "Netherlands") %>% ungroup %>% plot_anomaly_decomposition 

anomaly_summary %>% time_recompose() %>%
  plot_anomalies(time_recomposed = TRUE, ncol=3, color_no = "purple", color_yes = "orange", alpha_ribbon = 1)
```


#trying to get it to work for all countries
```{r}
selected_countries_new <- c("Sierra Leone")
Chicken_data_simple <- Chicken_data_normalised  %>%
  select(period_date, ratio, node) %>% 
   filter(node %in% selected_countries_new) %>% ungroup

#group_by(node) %>%
Chicken_data_simple %>% 
            time_decompose(ratio, method = "stl")%>% 
            anomalize(remainder, alpha = 5, method = "iqr") %>% time_recompose() %>%
  plot_anomalies(time_recomposed = TRUE, ncol=3, color_no = "purple", color_yes = "orange", alpha_ribbon = 1)

#plot_anomalies(time_recomposed = TRUE, ncol=3, color_no = "purple", color_yes = "orange", alpha_ribbon = 1)

#anomalies <- anomaly_summary %>% filter(anomaly == "Yes") %>% print

#anomaly_summary %>% filter(node == "Germany") %>% ungroup %>% plot_anomaly_decomposition 

#anomaly_summary %>% time_recompose() %>%
  #plot_anomalies(time_recomposed = TRUE, ncol=3, color_no = "purple", color_yes = "orange", alpha_ribbon = 1)
```

```{r}
above_ten <- Chicken_data_normalised  %>% group_by(node) %>% filter(n() > 15) %>%
  select(period_date, ratio, node) 


above_ten_analysed <-above_ten %>% 
            time_decompose(ratio, method = "stl") %>% anomalize(remainder, alpha = 5, method = "iqr") 

above_ten_anomalies <- above_ten_analysed %>% filter(anomaly == "Yes") %>% print

#anomalies <- anomaly_summary %>% filter(anomaly == "Yes") %>% print

anomaly_summary %>% filter(node == "Netherlands") %>% ungroup %>% plot_anomaly_decomposition 

anomaly_summary %>% time_recompose() %>%
  plot_anomalies(time_recomposed = TRUE, ncol=3, color_no = "purple", color_yes = "orange", alpha_ribbon = 1)

```

