---
title: "Network model attempt"
author: "Warren Thompson"
date: "27/03/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Required libraries
```{r}
require("RPostgreSQL")
library(ggplot2)
library(dplyr)
library(tidyverse)
library(tidygraph)
library(rlist)
library(gridExtra)
library(statnet)
library(texreg)
library(xergm)
library(btergm)
```

```{r}
source('get_Comtrade_monthly_data.R')
source('get_country_ids.R')
source('get_model_edges.R')
source('get_one_way_model_edges.R')
source('get_model_nodes.R')
source('get_trade_attributes.R')
source('get_trade_attributes_update.R')
```

#Attempt at modelling netwrok graphs of trade
```{r}
world_data   <- read.csv("world_cucumber_weight.csv", header = TRUE, sep = ",")

period_list               <- list() #List of months
net_list                  <- list() #Find network objects by index eg. net_list[[24]]
trade_matrix_list       <- list()

#Get data into months stored in list
world_monthly_data <- get_Comtrade_monthly_data(world_data)

#get unique ID for each country - use for nodes and edges later, prevent renaming of country with different ID each time loop runs
country_ids <-get_country_ids(world_data)
index = 0

for (i in world_monthly_data){
  index = index + 1
#Get some node attributes - we can definitely look more into this, Alex/Janis may have some ideas to include more node attributes
  month_trade_attributes  <- get_trade_attributes_test(i)
  
  #Get nodes and edges for model. reminder - NA generatedinvalid factor level     message result of get_model_nodes call, need to see what is casuing this and fix 
  nodes_model             <- get_model_nodes(month_data = i, month_trade_attributes,country_ids)
  edges_model             <- get_model_edges(nodes_model,month_data = i)
  edges_model             <- get_one_way_model_edges(edges_model)
  
  #Create covariate matrix of trade bewteen countries
  #mat <- diag(edges_model$trade_value_usd,nrow = nrow(edges_model),ncol = nrow(edges_model))
  #rownames(mat) <- edges_model$from
  #colnames(mat) <- edges_model$to
  
  mat <- diag(nodes_model$nett_trade, nrow = nrow(nodes_model),ncol = nrow(nodes_model))
  rownames(mat) <- nodes_model$id
  colnames(mat) <- nodes_model$id
  #Create edge covariate matrix based on trade ammoun
  trade_matrix_list[[index]] <- mat
  
  
  #Edges for network object
  only_edges             <- edges_model %>% select(c(2,1))
  
  #Create network object
  net <- network(only_edges, matrix.type = "edgelist", directed = T)
  
  #Add edge attributes
  net <- set.edge.attribute(net,"trade_value",edges_model$trade_value_usd)
  
  #Add some node attributes 
  net <- set.vertex.attribute(net, "nett_trade",nodes_model$nett_trade)
  #net <- set.vertex.attribute(net, "trade_flux",nodes_model$trade_flux)
  #net <- set.vertex.attribute(net, "trade_value",nodes_model$trade_value)
  #net <- set.vertex.attribute(net,"nett_weight",nodes_model$nett_weight)
  #net <- set.vertex.attribute(net, "trade_weight_value",nodes_model$trade_weight_value)
  
  #capture period
  month               <- unique(i$period)

  #Append features to respective lists
  period_list   <- list.append(period_list, month)
  net_list      <- list.append(net_list, net)
  
}

#Combine lists into dataframe
period_summary <- do.call(rbind, Map(data.frame, period=period_list))

#Convert period to date type
period_summary <- period_summary %>% mutate(period = paste0(period,"01")) %>% mutate(period = as.Date(period, "%Y%m%d"))

#Try covariate model without temperal component - very rough attempt, can have a look at including/dropping terms
model.1a <- btergm(net_list ~ edges + mutual + transitiveties  + nodecov("nett_trade") + nodecov("trade_flux") + nodecov("nett_weight"), R = 50, parallel = "snow",  ncpus = 3)

#See parameter estimates etc with 95% CI - how do we interpret these values?
summary(model.1a, level = 0.95)

#Goodness of fit test
gof.1a <- gof(model.1a, nsim = 5, statistics = c(esp,nsp,ideg,odeg))
plot(gof.1a)
dev.off()

#Try covariate model with temporal component - how to make list index a date? 
model.1b <- btergm(net_list ~ edges + mutual + transitiveties + nodeicov("trade_weight_value") + nodecov("nett_trade") + nodecov("trade_flux") +nodecov("nett_weight") + timecov(transform = function(t) t), R = 50, parallel = "snow",  ncpus = 3)

#See parameter estimates etc with 95% CI
summary(model.1b, level = 0.95)

#Goodness of fit test
gof.1b <- gof(model.1b, nsim = 5, statistics = c(esp, geodesic, deg))
plot(gof.1b)
dev.off()

#Try simplified covariate model without temperal component
model.1c <- btergm(net_list ~ edges + edgecov(trade_matrix_list) + transitiveties + twopath + isolates, R = 50, parallel = "snow",  ncpus = 2)

#See parameter estimates etc with 95% CI - how do we interpret these values?
#See Section 6 and Desmarais and Cranmer (2012a) for further details on interpretation of ERGMs and TERGMs.
summary(model.1c, level = 0.95)

#Goodness of fit test
gof.1c <- gof(model.1c, nsim = 5, statistics = c(esp,nsp,ideg,odeg))
plot(gof.1c)
dev.off()

#Test model by secting portion of network list and try simulate netwrok and compare to actual to test model
#1. Get model without most recent network
model.1d <- btergm(net_list[1:23] ~ edges + mutual + transitiveties + twopath, R = 50, parallel = "snow",  ncpus = 3)
#2. Test GOF by comparing simulated network with actual network
gof.1d <- gof(model.1d, nsim = 10, target = net_list[[24]], 
formula = net_list[1:23] ~ edges + mutual + transitiveties + twopath, coef = coef(model.1d),statistics = c(esp,nsp,ideg,odeg))

#Plot comparison
plot(gof.1d, roc.rgraph = TRUE, pr.rgraph = TRUE)
dev.off()

#Test probbility two nodes tied - try UK and Spain. i and j values from country_ids
interpret(model.1c, type = "tie", i = c(174), j = c(193), t = 15)

prob_vector <- vector()
#Loop through to get probability over time
for (time in 1:nrow(period_summary)){
  prob_values  <- interpret(model.1c, type = "node", i = c(174), j = c(193,33), t = time)
  prob_dat <- as.data.frame(prob_values,col.names = c("1"))
  prob_vector[time] <- prob_dat[[3,1]]
}

plot(period_summary$period,prob_vector)

#Check model degeneracy
checkdegeneracy(model.1d, nsim = 10)
```
