---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(rjson)
library(tidyverse)
library(comtradr)
library(ggplot2)
library(dplyr)
library(lubridate)
library(igraph)
library(tidygraph)
library(gridExtra)
```

```{r}
filename <- '012006-122018_0401_0402.RData'
load(filename)
```

```{r}
ignore <- list('World', 'EU-27', 'Other Asia, nes', 'Other Europe, nes', 'Areas, nes')
cc  <- cc[!(cc$partner %in% ignore) ,]
cc  <- cc[!(cc$reporter %in% ignore) ,]
```

```{r}
# Look up commodity descriptions related to "halibut"
ct_commodity_lookup("milk",return_code = FALSE,return_char = FALSE,verbose = TRUE)
```


```{r}
c1 <- cc[complete.cases(cc), ]
```

```{r}
sel_country <- c("Finland")
sel_trade <- "Exports"
```

```{r}
cc <- cc %>% filter(commodity_code == "0401")
```

```{r}
res1 <- cc %>% filter(reporter %in% sel_country) %>% filter(trade_flow == sel_trade) %>% group_by(period_date,reporter,commodity_code) %>% summarize(tote = sum(trade_value_usd)) %>% ungroup()
m1   <- res1 %>% group_by(reporter,commodity_code) %>% summarize(mtote = mean(tote)) %>% ungroup()
f1 <- inner_join(res1,m1,by=c("commodity_code","reporter")) %>% mutate(atote = tote/mtote)
res2 <- cc %>% filter(reporter %in% sel_country) %>% filter(trade_flow == sel_trade) %>% group_by(period_date,reporter,commodity_code) %>% summarize(tote = sum(net_weight_kg)) %>% ungroup()
m2   <- res2 %>% group_by(reporter,commodity_code) %>% summarize(mtote = mean(tote)) %>% ungroup()
f2 <- inner_join(res2,m2,by=c("commodity_code","reporter")) %>% mutate(atote = tote/mtote)
```

```{r}
#p1 <- ggplot(data = f1, aes(x=period_date,y=atote,color=commodity_code,shape=reporter)) +
p1 <- ggplot(data = res1, aes(x=period_date,y=tote,color=commodity_code,shape=reporter)) +
  geom_line() +
  #geom_smooth(span=0.5,method="loess",color="blue") +
  geom_point(size=2) +
  scale_y_log10() +
  scale_x_date(date_breaks = "3 month", date_labels = "%Y-%m") +
  ggtitle(paste(sel_trade,str_sub(filename,15,str_length(filename)-6),sep=" ")) +
  xlab("Year-Month") +
  ylab("Trade value $US") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
#p2 <- ggplot(data = f2, aes(x=period_date,y=atote,color=commodity_code,shape=reporter)) +
p2 <- ggplot(data = res2, aes(x=period_date,y=tote,color=commodity_code,shape=reporter)) +  
  geom_line() +
  #geom_smooth(span=0.5,method="loess",color="blue") +
  geom_point(size=2) +
  scale_y_log10() +
  scale_x_date(date_breaks = "3 month", date_labels = "%Y-%m") +
  ggtitle(paste(sel_trade,str_sub(filename,15,str_length(filename)-6),sep=" ")) +
  xlab("Year-Month") +
  ylab("Net Weight Kg") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
grid.arrange(p1, p2, ncol=2)
```

```{r}
res3 <- cc %>% filter(reporter %in% sel_country) %>% filter(trade_flow == sel_trade) %>% group_by(period_date,reporter) %>% summarize(tote = sum(trade_value_usd)) %>% ungroup()
res4 <- cc %>% filter(reporter %in% sel_country) %>% filter(trade_flow == sel_trade) %>% group_by(period_date,reporter) %>% summarize(tote = sum(net_weight_kg)) %>% ungroup()
```

```{r}
p3 <- ggplot(data = res3, aes(x=period_date,y=tote,shape=reporter)) +
  geom_line() +
  geom_smooth(span=0.25,method="loess",color="blue") +
  geom_point(size=2) +
  #scale_y_log10() +
  scale_x_date(date_breaks = "3 month", date_labels = "%Y-%m") +
  ggtitle(paste(sel_trade,str_sub(filename,15,str_length(filename)-6),sep=" ")) +
  xlab("Year-Month") +
  ylab("Trade value $US") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
p4 <- ggplot(data = res4, aes(x=period_date,y=tote,shape=reporter)) +
  geom_line() +
  geom_smooth(span=0.25,method="loess",color="blue") +
  geom_point(size=2) +
  #scale_y_log10() +
  scale_x_date(date_breaks = "3 month", date_labels = "%Y-%m") +
  ggtitle(paste(sel_trade,str_sub(filename,15,str_length(filename)-6),sep=" ")) +
  xlab("Year-Month") +
  ylab("Net Weight Kg") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
grid.arrange(p3,p4,ncol=2)
```
```{r}
res5 <- cc %>% filter(reporter %in% sel_country) %>% filter(trade_flow==sel_trade) %>% group_by(period_date,reporter,commodity_code,year_date) %>% summarize(tote=sum(trade_value_usd)) %>% ungroup()
res6 <- cc %>% filter(reporter %in% sel_country) %>% filter(trade_flow==sel_trade) %>% group_by(period_date,reporter,commodity_code,year_date) %>% summarize(tote=sum(net_weight_kg)) %>% ungroup()
```

```{r}
fy = list()
j <- 0
yearlist <- unique(res5$year_date)
for (i in yearlist){
  print(i)
  dd <- res5 %>% filter(year_date == i)
  nm <- length(unique(dd$period_date))
  if(nm == 12){
    j <- j + 1
    fy[j] <- i
  }
}
```
```{r}
res5 <- res5 %>% filter(year_date %in% fy)
res6 <- res6 %>% filter(year_date %in% fy)
```



```{r}
p5 <- ggplot(data=res5, aes(x=year_date, y=tote, fill=commodity_code)) +
  geom_bar(stat="identity") +
  scale_x_date(date_breaks = "1 year", date_labels = "%Y") +
  ggtitle(paste(sel_trade,str_sub(filename,15,str_length(filename)-6),sep=" ")) +
  xlab("Year") +
  ylab("Trade value $US")
p6 <- ggplot(data=res6, aes(x=year_date, y=tote, fill=commodity_code)) +
  geom_bar(stat="identity") +
  scale_x_date(date_breaks = "1 year", date_labels = "%Y") +
  ggtitle(paste(sel_trade,str_sub(filename,15,str_length(filename)-6),sep=" ")) +
  xlab("Year") +
  ylab("Net Weight Kg")
grid.arrange(p5,p6,ncol=2)
```





