---
title: Modelling of International trade
author: "Àlex Fabregat"
output:
  html_document: default
  html_notebook: default
  pdf_document:
    latex_engine: xelatex
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = FALSE, echo=TRUE)
```
```{r,message=FALSE,warning=FALSE,echo=FALSE}
library(RPostgreSQL)
library(tidyverse)
library(dbplyr)
library(rjson)
library(DBI)
library(lubridate)
library(tibble)
library(ggplot2)
library(stringr)
library(gridExtra)
library(network)
library(ggraph)
library(visNetwork)
library(networkD3)
library(igraph)
library(tidygraph)
library(cluster) 
library(fpc)
library(plotly)
library(rgl)
```
# Choose whether to read data from file or import via SQL
Set the variable to TRUE for importing *fresh* data from Comtrade via SQL setting the commodity code and time period.
```{r}
read_file = FALSE
#
if(read_file==TRUE){
source("get_Comtrade_data_all.R")
df <- get_Comtrade_data_all(201401,201601,"default","070700")
write.csv(df,'Comtrade_all.csv')
}else{
df <- read.csv(file="Comtrade_all.csv",header=TRUE)  
}
```

# Clean the missing data in the raw set (if any)
```{r}
df <- df[complete.cases(df),]
```

# Prepare data
```{r}
guys_2_remove <- c("EU-27","Areas, nes","Other Europe, nes","Other Africa, nes",
                   "Other Asia, nes","World")
df2 <- df %>% filter(!as.character(partner) %in% guys_2_remove) %>%
              filter(!as.character(reporter) %in% guys_2_remove)
df2 <- df2 %>% mutate(period_date = ymd(paste(period,"01",sep=""))) %>%
               mutate(year        = as.integer(str_sub(period,1,4))) %>%
               mutate(month       = as.integer(str_sub(period,5,6))) %>%
               mutate(price_usd_kg= trade_value_usd/netweight_kg)
Imports <- df2 %>% filter(trade_flow == "Imports") %>% select(-trade_flow,-X)
si <- Imports %>% select(period,reporter,partner,trade_value_usd) %>%
                  mutate(origin = as.character(partner)) %>%
                  mutate(destin = as.character(reporter)) %>% 
                  select(-reporter,-partner)
```

# I am sure this chunk can be largely improved code-wise
```{r}
month_list <- unique(si$period)
i <- 1
mylist <- list() #create an empty list
for (cur_month in month_list){
sity <- si %>% filter(period == cur_month) %>% transform(trade_value_usd  = as.numeric(trade_value_usd))
origin_country <- unique(sity$origin)
destin_country <- unique(sity$destin)
all_country    <- union(origin_country,destin_country)
for (cur_count in all_country) {
  
for_origin <- sity %>% filter(origin==cur_count) %>% summarize(a1 = sum(trade_value_usd),
                                                               b1 = n(),
                                                               c1 = mean(trade_value_usd),
                                                               d1 = max(trade_value_usd))

for_destin <- sity %>% filter(destin==cur_count) %>% summarize(a2 = sum(trade_value_usd),
                                                               b2 = n(),
                                                               c2 = mean(trade_value_usd),
                                                               d2 = max(trade_value_usd))
    vec <- list(10) #preallocate a vector. Shouldn't be a character but this is all I can do in R. Fix it later.
    #
    vec[1] <- cur_count
    vec[2] <- cur_month
    vec[3] <- for_origin$b1
    vec[4] <- for_origin$a1
    vec[5] <- for_origin$c1
    vec[6] <- for_origin$d1
    vec[7] <- for_destin$b2
    vec[8] <- for_destin$a2
    vec[9] <- for_destin$c2
    vec[10]<- for_destin$d2
  mylist[[i]] <- unlist(vec) #put all vectors in the list
  i <- i + 1
}
}
i <- i - 1
#
net_flux <- do.call("rbind",mylist)
net_flux <- data.frame(matrix(unlist(net_flux), nrow=i, byrow=F),stringsAsFactors = FALSE)

net_flux <- net_flux %>% rename(node   = X1)
net_flux <- net_flux %>% rename(period = X2)
net_flux <- net_flux %>% transform(X3  = as.integer(X3))  %>% rename( deg_out_wei = X3)
net_flux <- net_flux %>% transform(X4  = as.numeric(X4))  %>% rename( tot_out_wei = X4)
net_flux <- net_flux %>% transform(X5  = as.numeric(X5))  %>% rename( ave_out_wei = X5)
net_flux <- net_flux %>% transform(X6  = as.numeric(X6))  %>% rename( max_out_wei = X6)
net_flux <- net_flux %>% transform(X7  = as.integer(X7))  %>% rename( deg_in_wei  = X7)
net_flux <- net_flux %>% transform(X8  = as.numeric(X8))  %>% rename( tot_in_wei  = X8)
net_flux <- net_flux %>% transform(X9  = as.numeric(X9))  %>% rename( ave_in_wei  = X9)
net_flux <- net_flux %>% transform(X10 = as.numeric(X10)) %>% rename( max_in_wei  = X10)
net_flux <- net_flux %>% mutate(ratio = (tot_in_wei-tot_out_wei)/(tot_in_wei + tot_out_wei))
```

```{r}
tmp2 <- net_flux %>% mutate(period_date = ymd(paste(period,"01",sep="")))
tmp3 <- tmp2 %>%
    filter(node=="Netherlands") %>%
    mutate(month=month(period_date)) %>%
    mutate(quarter = ceiling(as.numeric(month) / 3))
x2 <- ggplot(NULL) +
    geom_point(data = tmp3,
    aes(x=tot_in_wei/1e6,y=ratio,color=quarter),size=3) +
    geom_path(data = tmp3, aes(x=tot_in_wei/1e6,y=ratio),alpha=0.1) +
    coord_cartesian(xlim = c(-1,30),ylim=c(-1,1)) +
    scale_colour_gradientn(colours=rainbow(4)) +
    labs(x="Total imports (thousands of tons)",
    y="Producer                        Distributor                        Consumer",
    title="Vertical axis: (Total imports - Total exports)/(Total imports + Total exports)",
    subtitle = "Temporal evolution for Netherlands")
x2
```


#This addresses Janis' request
```{r}
this_country <- "Netherlands"
some_stuff <- net_flux %>% mutate(period_date = ymd(paste(period,"01",sep="")))
nether <- some_stuff %>% filter(node==this_country)

time_history <- sort(unique(nether$period))

i <- 1
dat1 <- integer(1)
dat2 <- integer(1)
dat3 <- integer(1)
for (cur_time in time_history){
  junk1 <- some_stuff %>% filter(period == cur_time)
  netdf1 <- si %>% filter(period == cur_time) %>% select(origin,destin,trade_value_usd)
  sources1 <-      netdf1 %>% distinct(origin) %>% rename(label = origin)
  destinations1 <- netdf1 %>% distinct(destin) %>% rename(label = destin)
  per_route1 <- netdf1 %>% group_by(origin,destin) %>% summarise(weight = sum(trade_value_usd)/1e6) %>% ungroup()
  nodes1 <- full_join(sources1,destinations1,by="label")
  nodes1 <- nodes1 %>% rowid_to_column("id")
  edges1 <- per_route1 %>% left_join(nodes1,by=c("origin" = "label")) %>% rename(from = id)
  edges1 <- edges1     %>% left_join(nodes1,by=c("destin" = "label")) %>% rename(to   = id)
  edges1 <- select(edges1,from,to,weight)
  g <- tbl_graph(nodes = nodes1, edges = edges1, directed = TRUE)
    degree_val  <- degree(g)
    bet_val     <- betweenness(g)
    tri_no      <- count_triangles(g)
    this_one <- nodes1[nodes1$label==this_country,1]
    dat1[i] <- degree_val[this_one]
    dat2[i] <- bet_val[this_one]
    dat3[i] <- tri_no[this_one]
    i <- i + 1
  }

temp_data <- some_stuff %>% filter(node==this_country) %>% mutate(month=month(period_date),quarter = ceiling(as.numeric(month) / 3)) %>%
             arrange(period)
temp_data$degree_val <- sapply(dat1, paste0)
temp_data$bet_val    <- sapply(dat2, paste0)

temp_data$degree_val <- as.integer(temp_data$degree_val)
temp_data$bet_val    <- as.integer(temp_data$bet_val)
 
v1 <- ggplot(NULL) +
      geom_point(data = temp_data,
      aes(x=ratio,y=degree_val,color=quarter,size=tot_in_wei)) +
      scale_colour_gradientn(colours=rainbow(4)) +
      labs(x="Ratio",
           y="Degree",
      title = this_country)
v1
```