---
title: "HMRC_test"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Load libraries
```{r}
require("RPostgreSQL")
library(ggplot2)
library(dplyr)
library(tidyr)
library(knitr)
library(maptools)
library(stringr)
library(mapproj)
library(tidyverse)
library(rgdal)
library(ggmap)
library(maps)
library(mapdata)
library(mapproj)
library(rworldmap)
library(zoo)
library(e1071)
library(pscl)
library(ROCR)
```

# Open connection for HMRC data (UK's Revenue and Customs Authority)
```{r}
drv <- dbDriver("PostgreSQL")
con <- dbConnect(drv,
                 dbname = "hmrc",
                 host = "data-science-pgsql-dev-01.c8kuuajkqmsb.eu-west-2.rds.amazonaws.com",
                 user = "trade_read",
                 password = "2fs@9!^43g")
on.exit(dbDisconnect(con),add=TRUE)
on.exit(dbUnloadDriver(drv),add=TRUE)
(tab <- dbListTables(con))
```

# Import arrivals data with comcode < 30 
```{r}
ptm <- proc.time()
comcode    <- dbGetQuery(con, "SELECT * from comcode")
port       <- dbGetQuery(con, "SELECT * from port")
country    <- dbGetQuery(con, "SELECT * from country")
arrivals   <- dbGetQuery(con, "SELECT smk_comcode, smk_cod_alpha, smk_period_reference, smk_nett_mass, smk_no_of_consignments, smk_stat_value FROM arrivals WHERE smk_comcode ~ '^[0-2]'")
(proc.time() - ptm)
```

# Copy dataframe to have copy with full version of commodity code
```{r}
arrivals_copy <- arrivals
```

# Transform and reduce smk_comcode to two digit parent code 
```{r}
arrivals$smk_comcode <- substr(arrivals$smk_comcode, 1,2)
```

# Filter data to include only food comcode values < 24
```{r}
arrivals <- filter(arrivals, smk_comcode < 24)
```

