---
title: "HMRC_sql_easy"
date: "23/03/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

£We first create the connection to the database

```{r}

library(RPostgreSQL)
library(tidyverse)

drv <- dbDriver("PostgreSQL")
con <- dbConnect(drv,
                 dbname = "hmrc",
                 host = "data-science-pgsql-dev-01.c8kuuajkqmsb.eu-west-2.rds.amazonaws.com",
                 user = "trade_read",
                 password = "2fs@9!^43g")

```

We can use SQL in a chunk of a notebook

```{sql connection=con}

-- note that 1) I am using SQL notation here and 2) there is a connection reference in the definition of this chunk
SELECT * FROM arrivals WHERE smk_comcode ~ '^[0-2]'
-- we are not loading these data in a data frame, we are just querying the data

```

We can do the same in R

```{r}

# https://db.rstudio.com/dplyr/
arrivals_db <- tbl(con, 'arrivals')
  
result <- arrivals_db %>% 
  group_by(period) %>%
  tally()

# have alook at what result holds
# what kind of object is it? 

result <- result %>% collect()

# have another look at result
# what kind of object is it now?

```