---
title: "sql.access"
date: "22/03/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Load libraries
```{r}
require("RPostgreSQL")
```

# Function to access HMRC addtional info
```{r}
HMRC_add_info <- function(){

drv <- dbDriver("PostgreSQL")
con <- dbConnect(drv,
                 dbname = "hmrc",
                 host = "data-science-pgsql-dev-01.c8kuuajkqmsb.eu-west-2.rds.amazonaws.com",
                 user = "trade_read",
                 password = "2fs@9!^43g")

comcode    <- dbGetQuery(con, "SELECT * from comcode")
port       <- dbGetQuery(con, "SELECT * from port")
country    <- dbGetQuery(con, "SELECT * from country")

# R does not return multiobjects for return. Will return a list of dataframes that can be accessed via $ call. Example: Call function as HMRC_extra <- HMRC_add_info() To access comcode df use HMRC_extra$comcode 
return(list(comcode = as.data.frame(comcode), port = as.data.frame(port), country = as.data.frame(country)))
}

on.exit(dbDisconnect(con))
on.exit(dbUnloadDriver(drv))
```

# Call to HMRC sql db. Function requires df_name
```{r}
HMRC_sql_access <- function(df_name){

# Convert function inputs to strings
df_name <- as.character(substitute(df_name))

drv <- dbDriver("PostgreSQL")
con <- dbConnect(drv,
                 dbname = "hmrc",
                 host = "data-science-pgsql-dev-01.c8kuuajkqmsb.eu-west-2.rds.amazonaws.com",
                 user = "trade_read",
                 password = "2fs@9!^43g")

sql_db_query <- paste("SELECT * FROM",df_name,"WHERE smk_comcode ~ '^[0-2]'")
print("How about a cuppa?")
requested_df   <- dbGetQuery(con, sql_db_query)

return(requested_df = as.data.frame(requested_df))
}

on.exit(dbDisconnect(con))
on.exit(dbUnloadDriver(drv))
```

# Call to comtrade sql db. Function requires from_period and to_period in yyyymm format
```{r}
COM_sql_access <- function(from_period,to_period){

# Convert function inputs to strings
from_period <- as.character(substitute(from_period))
to_period <- as.character(substitute(to_period))

drv <- dbDriver("PostgreSQL")
con <- dbConnect(drv,
                 dbname = "comtrade",
                 host = "data-science-pgsql-dev-01.c8kuuajkqmsb.eu-west-2.rds.amazonaws.com",
                 user = "trade_read",
                 password = "2fs@9!^43g")

df_columns <- "classification, period, aggregate_level, is_leaf_code, trade_flow_code, trade_flow, reporter_code, reporter, partner_code, partner, commodity_code, netweight_kg, trade_value_usd"

sql_db_query <- paste("SELECT",df_columns,"FROM comtrade WHERE commodity_code ~ '^[0-2]' AND period >=",from_period,"AND period <=",to_period)
print("Large cuppa?")
comtrade   <- dbGetQuery(con, sql_db_query)

return(comtrade = as.data.frame(comtrade))
}

on.exit(dbDisconnect(con))
on.exit(dbUnloadDriver(drv))
```



